@WebAPI_HostAddress = https://localhost:7138

GET {{WebAPI_HostAddress}}/

###

@id=0
GET {{WebAPI_HostAddress}}/2

###

POST {{WebAPI_HostAddress}}/
Content-Type: application/json

{
  "title": "test title",
  "content": "test content"
}

###

DELETE {{WebAPI_HostAddress}}/3

###

PUT {{WebAPI_HostAddress}}/2
Content-Type: application/json

{
  "title": "updated title",
  "content": "updated content"
}

###
